### ISSUE TITLE
Dataset splited into small files

### ISSUE THREAD

**Issue by Jiaviz** [NVlabs/implicit_depth#2]
Hi, appreciations for your work! It's really not funny to download  this large dataset, after countless breakdown from browser or gdown command. 
Could you please split this dataset into small files? Thanks a lot!

**Comment by BboyHanat** [comment]
I was encountered this problem either, Have you download it ? If you download successfully, Can you share a copy to me? 
 I'm appreciate for that~

**Comment by Jiaviz** [comment]
> I was encountered this problem either, Have you download it ? If you download successfully, Can you share a copy to me? I'm appreciate for that~

I just give up TAT.

**Comment by BboyHanat** [comment]
> > I was encountered this problem either, Have you download it ? If you download successfully, Can you share a copy to me? I'm appreciate for that~
> 
> I just give up TAT.

I downloaded it, if you need, just email me

**Comment by Jiaviz** [comment]
@BobyHanat Sure, I'll bother you if I need it. By the way, it's incredible that you made it.
